
import type { Metadata } from "next";
import "./globals.css";


import ClientLayout from "./ClientLayout";

export const metadata: Metadata = {
  title: "LOGIN",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className="font-sans antialiased">
      <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  );
}